"use strict";
exports.__esModule = true;
var basic_types_1 = require("./basic-types");
console.log(basic_types_1.isACat("cat"));
console.log(basic_types_1.isACat("dog"));
console.log("");
console.log(basic_types_1.addNumbers(1, 2));
console.log("");
console.log(basic_types_1.introduction("Jack"));
console.log("");
basic_types_1.introducePerson("Molly");
console.log("");
console.log(basic_types_1.dumpObject("object", {}));
console.log("");
console.log(basic_types_1.dumpStringOrNumber("foo"));
console.log(basic_types_1.dumpStringOrNumber(10));
